void EXTI1_IRQHandler() iv IVT_INT_EXTI1 ics ICS_AUTO

{


}

void init_interrupt()

{
EnableInterrupts();
EXTI_IMR = EXTI_IMRbits.MR1|EXTI_IMRbits.MR1|EXTI_IMRbits.MR2|EXTI_IMRbits.MR3|EXTI_IMRbits.MR4|EXTI_IMRbits.MR5|EXTI_IMRbits.MR6|EXTI_IMRbits.MR7|EXTI_IMRbits.MR8;
EXTI_FTSR = EXTI_FTSRbits.TR1|EXTI_FTSRbits.TR2|EXTI_FTSRbits.TR3|EXTI_FTSRbits.TR4|EXTI_FTSRbits.TR5|EXTI_FTSRbits.TR6|EXTI_FTSRbits.TR7;
AFIO_EXTICR1 = 0x0000 ;
AFIO_EXTICR2 = 0x0000 ;
AFIO_EXTICR3 = 0x0000 ;
NVIC_IntEnable(IVT_INT_EXTI1);
}